### ISSUE TITLE
perfect-scrollbar plugin On reaching bottom, fires the event multiple times

### ISSUE THREAD

**Issue by ravi-mone** [utatti/perfect-scrollbar#669]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

When I used the `ps-y-reach-end` event, event fires more than once, when the scroll reached to the bottom of the container.

`document.addEventListener('ps-y-reach-end', (event)=> {
        console.log('Why this is printing multiple times when I reach Bottom, I wanted it to be single fire')
      });`

JSFiddle demo : https://jsfiddle.net/xv0rrxv3/460/

You can find more information here
https://stackoverflow.com/questions/45612153/perfect-scrollbar-plugin-on-reaching-bottom-fires-the-event-multiple-times

**Comment by ravi-mone** [comment]
perfect-scrollbar plugin On reaching bottom, fires the event multiple times

**Comment by utatti** [comment]
Actually I found this issue and fixed with d2021933a51d4eb739c7804506250ee308976366.

Thanks for your report!

**Comment by pdesai-tff** [comment]
@utatti The issue still remains for the ps-y-reach-start (It is however not there for the 'ps-y-reach-end' event as you mentioned)
